auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: MagicJiang.com
url: http://magicjiang.com
feed: /atom.xml
author_info: <a href="http://magicjiang.com/">MagicJiang</a>
